### PR TITLE
mole's Subterranian Sensors icon 

### PR DESCRIPTION
**Pull request by sav-chris**
The mole's SubterranianSensors icon was not enabled when researched and burrowed, this has been fixed

Includes mole fix in mod

### CODE REVIEW

**Comment by Solstice245** [comment]
I'm curious why these changes are being applied to the ScionExtension and ScionTester mods?

**Comment by sav-chris** [comment]
I figured the Keiron projects had been replaced by ScionExtension since that has all 3 races. I tested the ScionTester individually first.  Was adding it here redundant? The tester seems to need the change here as well. Should other projects know about the change?

I created a test map to demonstrate the change, is sharing that any use to you?

**Comment by Solstice245** [comment]
Data directly related to gameplay are located in the ScionMod and KeironMod, so changes to the data except in very special cases should be confined to those mods. Both ScionTester and ScionExtension inherit their data from these mods, which makes it so that you only need to change any particular datem in one place for it to be propagated to the rest.

**Comment by Solstice245** [comment]
I will be closing without merging as I have now fixed it within the ScionMod, but thank you for bringing this to my attention.

**Pull request closed without merging**
